export * as AuthorizeMb from "../f_AuthorizeMb/schema";
export * as CurrentUser from "../f_CurrentUser/schema";
export * as CurrentUserAddress from "../f_CurrentUser_Addresses/schema";
export * as Rides from "../f_Rides/schema";
export * as RidesSum from "../f_RidesSum/schema";
export * as Vehicles from "../f_Vehicles/schema";
export * as VehiclesOngoingRide from "../f_Vehicles_OngoingRide/schema";
export * as VehiclesStatus from "../f_Vehicles_Status/schema";
export * as VehiclesStatusOdometer from "../f_Vehicles_Status_Odometer/schema";
